# Generated by Django 4.2.3 on 2023-11-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Processing', max_length=20),
        ),
        migrations.AddField(
            model_name='pay_inf',
            name='card_num',
            field=models.IntegerField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
