# Generated by Django 4.2.3 on 2023-11-13 19:54

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_clinic_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default=1, upload_to=User.models.unique_image_customer),
            preserve_default=False,
        ),
    ]
