# Generated by Django 4.2.3 on 2023-11-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_customer_image_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='price',
            field=models.FloatField(),
        ),
    ]
