# Generated by Django 4.2.3 on 2023-11-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_rent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rent',
            name='duration_months',
            field=models.IntegerField(editable=False),
        ),
    ]
