# Generated by Django 4.2.3 on 2023-11-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
