# Generated by Django 4.2.3 on 2023-11-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(editable=False),
        ),
    ]
