# Generated by Django 4.2.3 on 2023-11-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_category_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
